config/routes.rb
Rails.application.routes.draw do
  resources :post_notifications
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_notification.rb
class PostNotification < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_notifications_controller.rb
class PostNotificationsController < ApplicationController
  before_action :set_post_notification, only: %i[ show edit update destroy ]

  # GET /post_notifications or /post_notifications.json
  def index
    @post_notifications = PostNotification.all
  end

  # GET /post_notifications/1 or /post_notifications/1.json
  def show
  end

  # GET /post_notifications/new
  def new
    @post_notification = PostNotification.new
  end

  # GET /post_notifications/1/edit
  def edit
  end

  # POST /post_notifications or /post_notifications.json
  def create
    @post_notification = PostNotification.new(post_notification_params)

    respond_to do |format|
      if @post_notification.save
        format.html { redirect_to post_notification_url(@post_notification), notice: "Post notification was successfully created." }
        format.json { render :show, status: :created, location: @post_notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_notifications/1 or /post_notifications/1.json
  def update
    respond_to do |format|
      if @post_notification.update(post_notification_params)
        format.html { redirect_to post_notification_url(@post_notification), notice: "Post notification was successfully updated." }
        format.json { render :show, status: :ok, location: @post_notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_notifications/1 or /post_notifications/1.json
  def destroy
    @post_notification.destroy

    respond_to do |format|
      format.html { redirect_to post_notifications_url, notice: "Post notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_notification
      @post_notification = PostNotification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_notification_params
      params.require(:post_notification).permit(:post_id, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

    PostNotificationJob.perform_later(@post)
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_notifications_helper.rb
module PostNotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post_notifications/_form.html.erb
<%= form_with(model: post_notification) do |form| %>
  <% if post_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_notification.errors.count, "error") %> prohibited this post_notification from being saved:</h2>

      <ul>
        <% post_notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_notifications/edit.html.erb
<h1>Editing Post Notification</h1>

<%= render 'form', post_notification: @post_notification %>

<%= link_to 'Show', @post_notification %> |
<%= link_to 'Back', post_notifications_path %>

app/views/post_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_notifications.each do |post_notification| %>
      <tr>
        <td><%= post_notification.post_id %></td>
        <td><%= post_notification.message %></td>
        <td><%= link_to 'Show', post_notification %></td>
        <td><%= link_to 'Edit', edit_post_notification_path(post_notification) %></td>
        <td><%= link_to 'Destroy', post_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Notification', new_post_notification_path %>

app/views/post_notifications/new.html.erb
<h1>New Post Notification</h1>

<%= render 'form', post_notification: @post_notification %>

<%= link_to 'Back', post_notifications_path %>

app/views/post_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_notification.post_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @post_notification.message %>
</p>

<%= link_to 'Edit', edit_post_notification_path(@post_notification) %> |
<%= link_to 'Back', post_notifications_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>